version: "4"
services:
  postgres_backstage:
    container_name: postgres_backstage
    image: postgres:17-alpine
    ports:
      - "5632:5432"
    environment:
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
      POSTGRES_DB: backstage
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - backstage

volumes:
  data-postgres:
    name: postgres_backstage

networks:
  backstage:
    name: backstage