apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: product-service
  description: Product Service.
  tags:
    - java
  links:
    - url: https://github.com/le03nava/LifeControl.git
      title: Source Code
      icon: github
    - url: https://LifeControl/product-service.com
      title: Production
      icon: globe
  annotations:
    # this could also be `url:<url>` if the documentation isn't in the same location
    backstage.io/techdocs-ref: url:https://github.com/le03nava/LifeControl/tree/main/docs/product-service
    #github.com/project-slug: 0GiS0/tour-of-heroes-dotnet-api
spec:
  type: openapi
  lifecycle: production
  owner: user:0GiS0
  system: tour-of-heroes
  #dependsOn: ['resource:heroes-db']
  #apiConsumedBy: ['component:www-heroes']
  definition:
    $text: https://github.com/le03nava/LifeControl/blob/main/product-service/docs/api-docs.json
