#!/bin/bash
# ============================================
# LifeControl - Environment Setup Script
# ============================================

set -e

# Docker directory
DOCKER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check environment argument
ENV=${1:-dev}

# Environment files
case "$ENV" in
dev | development)
	ENV_FILE="$DOCKER_DIR/.env.dev"
	VOLUMES_SUFIJO="volumes-dev"
	NETWORK_NAME="lifecontrol-network-dev"
	print_status "Setting up DEVELOPMENT environment"
	;;
staging | stg)
	ENV_FILE="$DOCKER_DIR/.env.staging"
	VOLUMES_SUFIJO="volumes-staging"
	NETWORK_NAME="lifecontrol-network-staging"
	print_status "Setting up STAGING environment"
	;;
prod | production)
	ENV_FILE="$DOCKER_DIR/.env.prod"
	VOLUMES_SUFIJO="volumes-prod"
	NETWORK_NAME="lifecontrol-network-prod"
	print_status "Setting up PRODUCTION environment"
	;;
*)
	print_error "Invalid environment: $ENV"
	echo "Usage: $0 [dev|staging|prod]"
	exit 1
	;;
esac

# Check if env file exists
if [ ! -f "$ENV_FILE" ]; then
	print_error "Environment file $ENV_FILE not found!"
	print_status "Creating from template..."
	cp "$DOCKER_DIR/.env.template" "$ENV_FILE"
	print_success "Created $ENV_FILE"
	print_warning "Please edit $ENV_FILE and fill in the values"
	exit 1
fi

print_status "Using environment file: $ENV_FILE"

# Check Docker first (before creating network)
if ! docker info >/dev/null 2>&1; then
	print_error "Docker is not running!"
	exit 1
fi
print_success "Docker is running"

# Network is now handled by docker-compose default network
# No need to create external network anymore
# The default bridge network will be used automatically

# Create volume directories
print_status "Creating volume directories..."
mkdir -p docker/${VOLUMES_SUFIJO}/{mongodb/data,mysql/data,postgres/{data,product,lifecontrol},kafka/data,keycloak/realms,prometheus/{data,config},grafana/{data,config},tempo/{data,config},loki/{data,config}}
mkdir -p docker/${VOLUMES_SUFIJO}/mysql/init
print_success "Volume directories created"

# Copy selected environment file to .env (in docker dir)
cp "$ENV_FILE" "$DOCKER_DIR/.env"
print_success "Copied $ENV_FILE to $DOCKER_DIR/.env"

# Add dynamic environment variables to .env
print_status "Adding dynamic environment variables..."
cat >>"$DOCKER_DIR/.env" <<EOF

# Dynamic variables (do not edit manually)
# Generated by setup-env.sh
VOLUMES_BASE_PATH=./docker/${VOLUMES_SUFIJO}
NETWORK_NAME=${NETWORK_NAME}
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-lifecontrol}
EOF
print_success "Dynamic variables added to .env"

# For production, check secrets
if [ "$ENV" = "prod" ] || [ "$ENV" = "production" ]; then
	print_status "Checking secrets..."
	if [ ! -f "$DOCKER_DIR/.env.secrets" ]; then
		print_error "Secrets file $DOCKER_DIR/.env.secrets not found!"
		print_status "Creating template..."
		cp "$DOCKER_DIR/.env.secrets.template" "$DOCKER_DIR/.env.secrets"
		print_warning "Please edit $DOCKER_DIR/.env.secrets and fill in the values"
	else
		print_success "Secrets file found"
	fi

	# Create secrets directory
	mkdir -p secrets
fi

print_success "Environment setup completed!"
print_status "Run 'docker-compose up -d' to start services"

# Show service URLs
echo ""
print_status "Service URLs:"
echo "=========================================="
case "$ENV" in
dev)
	echo -e "${GREEN}API Gateway:${NC}      http://localhost:9000"
	echo -e "${GREEN}Keycloak:${NC}         http://localhost:8181"
	echo -e "${GREEN}Grafana:${NC}          http://localhost:3000"
	echo -e "${GREEN}Prometheus:${NC}       http://localhost:9090"
	echo -e "${GREEN}Loki:${NC}            http://localhost:3100"
	echo -e "${GREEN}Kafka UI:${NC}         http://localhost:8086"
	;;
staging)
	echo -e "${GREEN}API Gateway:${NC}      http://localhost:9100"
	echo -e "${GREEN}Keycloak:${NC}         http://localhost:8281"
	echo -e "${GREEN}Grafana:${NC}          http://localhost:3100"
	echo -e "${GREEN}Prometheus:${NC}       http://localhost:9190"
	;;
prod)
	echo -e "${GREEN}API Gateway:${NC}      http://localhost:9200"
	echo -e "${GREEN}Keycloak:${NC}         http://localhost:8381"
	echo -e "${GREEN}Grafana:${NC}          http://localhost:3200"
	echo -e "${GREEN}Prometheus:${NC}       http://localhost:9290"
	;;
esac
echo "=========================================="
