#!/bin/sh
set -e

echo "========================================="
echo "LifeControl - Loading Configuration"
echo "========================================="

echo "[INFO] Generating env.js with environment variables..."

# Keycloak config
KEYCLOAK_URL_VAL="${KEYCLOAK_URL:-http://localhost:8181}"
KEYCLOAK_REALM_VAL="${KEYCLOAK_REALM:-life-control-realm}"
KEYCLOAK_CLIENT_ID_VAL="${KEYCLOAK_CLIENT_ID:-life-control-client}"

# API Gateway config
API_GATEWAY_URL_VAL="${API_GATEWAY_URL:-http://localhost:9000}"
API_BASE_PATH_VAL="${API_BASE_PATH:-/api/product}"

echo "[INFO] Keycloak URL: $KEYCLOAK_URL_VAL"
echo "[INFO] Keycloak Realm: $KEYCLOAK_REALM_VAL"
echo "[INFO] Keycloak Client ID: $KEYCLOAK_CLIENT_ID_VAL"
echo "[INFO] API Gateway URL: $API_GATEWAY_URL_VAL"
echo "[INFO] API Base Path: $API_BASE_PATH_VAL"

# Generar env.js con los valores de entorno
cat >/app/public/assets/env.js <<EOF
// Environment configuration loaded before Angular app
// Generated by entrypoint.sh - Do not edit manually
(function(window) {
  window.env = {
    KEYCLOAK_URL: '$KEYCLOAK_URL_VAL',
    KEYCLOAK_REALM: '$KEYCLOAK_REALM_VAL',
    KEYCLOAK_CLIENT_ID: '$KEYCLOAK_CLIENT_ID_VAL',
    API_GATEWAY_URL: '$API_GATEWAY_URL_VAL',
    API_BASE_PATH: '$API_BASE_PATH_VAL'
  };
})(window);
EOF

echo "[INFO] Configuration file contents:"
cat /app/public/assets/env.js
echo "========================================="

exec "$@"
