#!/bin/sh
set -e

echo "========================================="
echo "LifeControl - Loading Configuration"
echo "========================================="

echo "[INFO] Generating env.js with environment variables..."

# Directorio donde nginx sirve la SPA (non-root, escribible por USER 1000:1000)
HTML_DIR="/usr/share/nginx/html"

# Keycloak config
KEYCLOAK_URL_VAL="${KEYCLOAK_URL:-http://localhost:8181}"
KEYCLOAK_REALM_VAL="${KEYCLOAK_REALM:-life-control-realm}"
KEYCLOAK_CLIENT_ID_VAL="${KEYCLOAK_CLIENT_ID:-life-control-client}"

# API Gateway config
API_GATEWAY_URL_VAL="${API_GATEWAY_URL:-http://localhost:9000}"
API_BASE_PATH_VAL="${API_BASE_PATH:-/api}"

echo "[INFO] Keycloak URL: $KEYCLOAK_URL_VAL"
echo "[INFO] Keycloak Realm: $KEYCLOAK_REALM_VAL"
echo "[INFO] Keycloak Client ID: $KEYCLOAK_CLIENT_ID_VAL"
echo "[INFO] API Gateway URL: $API_GATEWAY_URL_VAL"
echo "[INFO] API Base Path: $API_BASE_PATH_VAL"

# Escapar para JSON de forma segura (backslash y comilla doble). Estos valores
# son URLs/identificadores, nunca traen newlines ni control chars, así que
# alcanza con escapar esos dos caracteres.
json_escape() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

mkdir -p "$HTML_DIR/assets"

cat > "$HTML_DIR/assets/env.js" <<EOF
// Environment configuration loaded before Angular app
// Generated by entrypoint.sh - Do not edit manually
(function(window) {
  window.env = {
    KEYCLOAK_URL: "$(json_escape "$KEYCLOAK_URL_VAL")",
    KEYCLOAK_REALM: "$(json_escape "$KEYCLOAK_REALM_VAL")",
    KEYCLOAK_CLIENT_ID: "$(json_escape "$KEYCLOAK_CLIENT_ID_VAL")",
    API_GATEWAY_URL: "$(json_escape "$API_GATEWAY_URL_VAL")",
    API_BASE_PATH: "$(json_escape "$API_BASE_PATH_VAL")"
  };
})(window);
EOF

# =========================================
# Content Security Policy
# =========================================

# Nonce de un solo uso para el script env.js (regenerado en cada boot)
# Uso /dev/urandom + od (POSIX, sin dependencia de openssl)
CSP_NONCE="$(od -An -N16 -tx1 /dev/urandom | tr -d ' \n')"

# Orígenes (scheme://host:port) para API Gateway y Keycloak, derivados de env
API_GATEWAY_ORIGIN="$(printf '%s' "$API_GATEWAY_URL_VAL" | sed 's@^\([a-zA-Z][a-zA-Z0-9+.-]*://[^/]*\).*@\1@')"
KEYCLOAK_ORIGIN="$(printf '%s' "$KEYCLOAK_URL_VAL" | sed 's@^\([a-zA-Z][a-zA-Z0-9+.-]*://[^/]*\).*@\1@')"

# Solo se inyectan en la CSP si matchean un formato estricto scheme://host[:port]
# (evita que un env malicioso cuele directivas tipo "; script-src 'unsafe-inline'").
valid_origin() {
  printf '%s' "$1" | grep -Eq '^[a-zA-Z][a-zA-Z0-9+.-]*://[A-Za-z0-9.-]+(:[0-9]+)?$'
}

CSP_API_ORIGIN=""
if valid_origin "$API_GATEWAY_ORIGIN"; then
  CSP_API_ORIGIN="$API_GATEWAY_ORIGIN"
else
  echo "[WARN] API Gateway origin inválido, omitido de la CSP: '$API_GATEWAY_ORIGIN'"
fi

CSP_KEYCLOAK_ORIGIN=""
if valid_origin "$KEYCLOAK_ORIGIN"; then
  CSP_KEYCLOAK_ORIGIN="$KEYCLOAK_ORIGIN"
else
  echo "[WARN] Keycloak origin inválido, omitido de la CSP: '$KEYCLOAK_ORIGIN'"
fi

echo "[INFO] CSP nonce: $CSP_NONCE"
echo "[INFO] API Gateway origin: $API_GATEWAY_ORIGIN"
echo "[INFO] Keycloak origin: $KEYCLOAK_ORIGIN"

# Política generada en runtime: los orígenes de API/Keycloak se inyectan en
# connect-src y frame-src porque son dinámicos (desconocidos en build time).
CONTENT_SECURITY_POLICY="default-src 'self'; script-src 'self' 'nonce-${CSP_NONCE}'; style-src 'self' 'unsafe-inline'; connect-src 'self'${CSP_API_ORIGIN:+ ${CSP_API_ORIGIN}}${CSP_KEYCLOAK_ORIGIN:+ ${CSP_KEYCLOAK_ORIGIN}}; img-src 'self' data: https:; font-src 'self'; object-src 'none'; base-uri 'self'; frame-src 'self'${CSP_KEYCLOAK_ORIGIN:+ ${CSP_KEYCLOAK_ORIGIN}}"

# 1) Reemplazar la meta CSP por la política generada (con nonce y orígenes reales)
sed -i "s|<meta http-equiv=\"Content-Security-Policy\" content=\"[^\"]*\">|<meta http-equiv=\"Content-Security-Policy\" content=\"${CONTENT_SECURITY_POLICY}\">|" "$HTML_DIR/index.html"

# 2) Inyectar el nonce en el script tag de env.js
sed -i "s|__CSP_NONCE__|${CSP_NONCE}|g" "$HTML_DIR/index.html"

echo "[INFO] Configuration file contents:"
cat "$HTML_DIR/assets/env.js"
echo "========================================="

exec "$@"
